app.jwt.secret-key=4ec7caf8b881559d0c8af28ceb42f04f0aef3d2143bf3b13f2225ee75b141869
# The JWT token duration in days
app.jwt.duration=10

app.datasource.database=duan1_dev
app.datasource.username=sa
app.datasource.password=Lovanky6408

app.static.image.path=/home/lovanky/Uploads/Duan1/